import type { Article } from '@/types/domain';

export const DAILY_ARTICLES: Article[] = [
  {
    id: 'daily-cet4-city-trees',
    title: 'Why Cities Need More Trees',
    summary: '从城市树木出发，理解自然如何影响我们的日常生活。',
    article:
      'Cities around the world are planting more trees. Trees make streets cooler, clean the air, and give birds a place to live. They can also help people feel calmer. A city tree may look simple, but it works every day. Its leaves provide shade in summer, while its roots hold water after heavy rain. For these reasons, many communities now treat trees as an important part of city planning.',
    questions: [
      { question: '文章主要说明了什么？', options: ['城市树木的作用', '如何建造房屋', '鸟类迁徙路线', '夏季旅行计划'], answer: 0 },
      { question: '树根可以帮助什么？', options: ['制造噪音', '保存雨水', '增加交通', '改变季节'], answer: 1 },
      { question: '作者对城市种树持什么态度？', options: ['支持', '反对', '担忧', '无所谓'], answer: 0 },
    ],
    difficulty: 'CET4',
    vocabHitIds: [],
    createdAt: Date.now(),
    wordCount: 105,
    estimatedMinutes: 2,
    topic: '自然',
    source: 'daily',
    publishDate: new Date().toISOString().slice(0, 10),
    coverUrl: 'https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=1200&q=82',
  },
  {
    id: 'daily-cet6-digital-focus',
    title: 'The Cost of Constant Connection',
    summary: '通知为何不断打断注意力，以及我们如何重新掌控数字生活。',
    article:
      'Digital tools make communication immediate, but constant connection has a hidden cost. Each notification asks the brain to switch attention, and returning to the original task takes time. Researchers suggest that people create periods of deliberate disconnection. Turning off unnecessary alerts, placing the phone out of reach, and scheduling time for messages can reduce mental pressure without rejecting technology altogether.',
    questions: [
      { question: '持续收到通知的主要问题是什么？', options: ['设备更贵', '注意力频繁切换', '网络变慢', '信息会消失'], answer: 1 },
      { question: '作者建议怎样处理消息？', options: ['完全不用手机', '立即回复全部消息', '安排固定时间查看', '购买新设备'], answer: 2 },
      { question: '文章对科技的态度是什么？', options: ['全面否定', '理性使用', '盲目推崇', '完全无关'], answer: 1 },
    ],
    difficulty: 'CET6',
    vocabHitIds: [],
    createdAt: Date.now(),
    wordCount: 128,
    estimatedMinutes: 3,
    topic: '科技',
    source: 'daily',
    publishDate: new Date().toISOString().slice(0, 10),
    coverUrl: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1200&q=82',
  },
  {
    id: 'daily-postgrad-memory',
    title: 'Memory Is an Act of Reconstruction',
    summary: '记忆并非录像，而是大脑不断重建过去的过程。',
    article:
      'Human memory is often compared to a recording, yet psychologists describe it as a process of reconstruction. When people recall an event, they combine stored details with later knowledge and present expectations. This flexibility allows memory to remain useful, but it also makes recollection vulnerable to distortion. Understanding this process matters in classrooms, interviews, and courts, where confidence is sometimes mistaken for accuracy.',
    questions: [
      { question: '心理学家如何描述记忆？', options: ['固定录像', '重建过程', '生理疾病', '语言能力'], answer: 1 },
      { question: '记忆为什么可能失真？', options: ['信息完全消失', '回忆会结合后来的知识', '人们拒绝思考', '大脑无法储存细节'], answer: 1 },
      { question: '文章最后强调了什么？', options: ['信心等于准确', '记忆只用于课堂', '理解记忆机制很重要', '法庭不需要证词'], answer: 2 },
    ],
    difficulty: '考研',
    vocabHitIds: [],
    createdAt: Date.now(),
    wordCount: 143,
    estimatedMinutes: 3,
    topic: '教育',
    source: 'daily',
    publishDate: new Date().toISOString().slice(0, 10),
    coverUrl: 'https://images.unsplash.com/photo-1456406644174-8ddd4cd52a06?auto=format&fit=crop&w=1200&q=82',
  },
  {
    id: 'daily-ielts-circular-cities',
    title: 'Can a City Become Circular?',
    summary: '城市如何减少浪费，并把废弃材料重新带回生产系统。',
    article:
      'The circular city is an emerging approach to urban sustainability. Instead of treating used materials as waste, circular systems keep resources in use through repair, sharing, and recycling. The transition requires more than household behaviour: buildings must be designed for reuse, businesses need incentives to recover products, and local governments must coordinate infrastructure. Although the model is difficult to implement, it offers cities a practical way to reduce environmental pressure while supporting innovation.',
    questions: [
      { question: '循环城市的核心是什么？', options: ['扩大城市边界', '让资源持续使用', '减少公共交通', '增加一次性产品'], answer: 1 },
      { question: '转型需要哪些主体参与？', options: ['只有家庭', '只有企业', '家庭、企业和政府', '只有设计师'], answer: 2 },
      { question: '作者如何评价这一模式？', options: ['容易但无效', '困难但有实际价值', '已经完全成熟', '只适用于农村'], answer: 1 },
    ],
    difficulty: '雅思',
    vocabHitIds: [],
    createdAt: Date.now(),
    wordCount: 157,
    estimatedMinutes: 4,
    topic: '生活',
    source: 'daily',
    publishDate: new Date().toISOString().slice(0, 10),
    coverUrl: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?auto=format&fit=crop&w=1200&q=82',
  },
  {
    id: 'daily-toefl-ocean-sound',
    title: 'Listening to the Changing Ocean',
    summary: '科学家利用水下声音观察海洋生态系统的细微变化。',
    article:
      'Marine researchers increasingly use sound to study ecosystems that are difficult to observe directly. Underwater microphones can record whales, fish, ships, and even the movement of ice over long periods. By comparing these acoustic patterns, scientists detect changes in migration, biodiversity, and human activity. Sound does not replace visual surveys, but it provides a continuous stream of evidence from remote environments where regular fieldwork would be expensive or dangerous.',
    questions: [
      { question: '水下麦克风的优势是什么？', options: ['能够连续收集证据', '可以阻止船只航行', '完全取代视觉调查', '只能记录鲸鱼'], answer: 0 },
      { question: '声音数据可以反映什么？', options: ['建筑成本', '迁徙和生物多样性', '空气污染', '农业生产'], answer: 1 },
      { question: '作者如何看待声学研究？', options: ['视觉调查的补充', '没有实际价值', '只适合浅水区', '会增加野外风险'], answer: 0 },
    ],
    difficulty: '托福',
    vocabHitIds: [],
    createdAt: Date.now(),
    wordCount: 151,
    estimatedMinutes: 4,
    topic: '自然',
    source: 'daily',
    publishDate: new Date().toISOString().slice(0, 10),
    coverUrl: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1200&q=82',
  },
];
